### ISSUE TITLE
Parsing Binary Numbers Fails

### ISSUE THREAD

**Issue by ManuelLerchner** [ManuelLerchner/analyzer#1]
I can't get the sample code from the slides to parse correctly. This means Goblint can't even start to analyze it.

```c
#include <assert.h>
#include <stdlib.h>

#define ANY_ERROR 0b0101  // 5
int main() {
  int state;
  int r = rand() % 3;  // {r 7→ [0; 2],state 7→ [MIN INT; MAX INT]}
  switch (r) {
    case 0:
      state = 0b0000; /* 0 */
      break;
    case 1:
      state = 0b1000; /* 8 */
      break;
    default:
      state = 0b1010; /* 10 */
      break;
  }
  // {r 7→ [0; 2],state 7→ [0; 10]}
  assert((state & ANY_ERROR) == 0);
}
```

I think it's caused by https://github.com/BinaryAnalysisPlatform/FrontC not being able to parse the binary numbers (`0b0000`, `0b1000`, `0b1010`). 

**FIX:** For now, it's fine to just rewrite all the binary numbers into their decimal form. But someone should look into this theory and maybe try to fix it

**Comment by Draggon01** [comment]
@ManuelLerchner Problem is for sure in the [FrontC](https://github.com/BinaryAnalysisPlatform/FrontC) library, it does not support parsing by 0b prefix as it is not part of any c standard, just an addon in gcc and clang, so I dont know if this is something we can or should implement in goblint or anywhere else...

probably we can start a discussion in their github issues, but I don't know if this will lead to anything else than them telling us that this is not in the standard.
